<?php

/**
 * Implements hook_menu().
 */
function bibdk_search_controls_menu() {
  $items['admin/config/search/bibdk_search_controls'] = array(
    'title'             => 'Bibliotek.dk search controls',
    'description'       => 'Edit search controls (sort, size, format, etc.).',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('bibdk_search_controls_admin'),
    'access arguments'  => array('administer search'),
    'file'              => 'bibdk_search_controls.admin.inc',
  );
  $items['admin/config/search/bibdk_search_controls/%/edit'] = array(
    'title'             => 'Edit search control',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('bibdk_search_controls_edit', 4),
    'access arguments'  => array('administer search'),
    'file'              => 'bibdk_search_controls.admin.inc',
  );
  $items['admin/config/search/bibdk_search_controls/%/delete'] = array(
    'title'             => 'Edit search control',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('bibdk_search_controls_delete', 4),
    'access arguments'  => array('administer search'),
    'file'              => 'bibdk_search_controls.admin.inc',
  );
  $items['admin/config/search/bibdk_search_controls/%/delete_value/%'] = array(
    'title'             => 'Edit search control',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('bibdk_search_controls_delete_value', 4, 6),
    'access arguments'  => array('administer search'),
    'file'              => 'bibdk_search_controls.admin.inc',
  );
  return $items;
}


/**
 * Implements hook_form_search_block_form_alter().
 */
function bibdk_search_controls_form_search_block_form_alter(&$form, &$form_state, $form_id) {
  $controls = variable_get('bibdk_search_controls',array());
  dpm(serialize($controls));
  foreach ( $controls as $key => $control ) {
    $name = $control['name'];
    $default_value = '';
    $default_values = array();
    foreach ( $controls[$key]['values'] as $n => $value ) {
      $default_values[] = ( $value['default'] ) ? $value['value'] : NULL;
    }
    if (  $controls[$key]['type'] == 'checkboxes' ) {
        $default_value = check_plain(implode('|',$default_values));
        $default_value = ( isset($_GET[$name]) ) ? check_plain(implode('|',$_GET[$name])) : $default_value;
    } else {
        $default_value = check_plain(implode('',$default_values));
        $default_value = ( isset($_GET[$name]) ) ? check_plain($_GET[$name]) : $default_value;
    }
    $form[ $control['name'] ] = array(
      '#type' => 'hidden',
      '#default_value' => $default_value,
      '#attributes' => array('id' => 'controls_search_' . $control['name']),
    );
  }
  return $form;
}


/**
 * Implements hook_block_info().
 */
function  bibdk_search_controls_block_info() {
  // configure default menu for user help content.
  $controls = variable_get('bibdk_search_controls',array());

  foreach ($controls as $key => $control) {
    $title = $control['title'];
    $blocks['bibdk-search-control-' . $key] = array(
      'title' => '<none>',
      'info' => t('Bibliotek.dk search control block : ' . $title),
      'cache' => DRUPAL_CACHE_GLOBAL,
    );
  }

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function  bibdk_search_controls_block_view($delta = '') {
  $block = array();
  $controls = variable_get('bibdk_search_controls',array());
  foreach ( $controls as $key => $control ) {
    if ( $delta == 'bibdk-search-control-' . $key ) {
      $block['subject'] = t('Bibliotek.dk search control : ' . $control['title'] );
      $block['content'] = drupal_get_form('bibdk_search_controls_form', $key);
      $block['title'] = '<none>';
      return $block;
    }
  }
  return $block;
}


/**
 * Edit search control form
 */
function bibdk_search_controls_form($form, &$form_state, $key) {

  $form = array();
  $controls = variable_get('bibdk_search_controls',array());
  $default_value = NULL;

  if ( isset( $controls[$key] ) ) {
    $name = $controls[$key]['name'];
    if ( !empty($controls[$key]['values']) ) {
      foreach ( $controls[$key]['values'] as $n => $value ) {
        $values[ $value['value'] ] = t($value['label'], array(), array('context' => 'bibdk_search_controls')) ;
        if (  $controls[$key]['type'] == 'checkboxes' ) {
          $default_value[$n] = ( $value['default'] ) ? $value['value'] : NULL;
        }
        else {
          $default_value = ( $value['default'] ) ? $value['value'] : NULL;
        }
      }
      if (  $controls[$key]['type'] == 'checkboxes' ) {
        if ( isset($_GET[$name]) && is_array($_GET[$name]) ) {
          foreach ( $_GET[$name] as $i => $val ) {
            $default_value[] = check_plain($val);
          }
        }
      }
      else {
        $default_value = isset($_GET[$name]) ? check_plain($_GET[$name]) : $default_value;
      }
      $form[ $name ] = array(
        '#type'           => $controls[$key]['type'],
        '#options'        => $values,
        '#default_value'  => $default_value,
        '#title'          => t($controls[$key]['label'], array(), array('context' => 'bibdk_search_controls')),
        '#description'    => t($controls[$key]['description'], array(), array('context' => 'bibdk_search_controls')),
      );
      $form['#attached']['js'] = array(
        drupal_get_path('module', 'bibdk_search_controls') . '/js/bibdk_search_controls.js',
      );
      $form['#attributes'] = array(
        'class' => array('bibdk-search-controls-form'),
        'data'  => array('controls_search_' . $name),
      );
      $form['#theme'] = 'bibdk_search_controls-' . $controls[$key]['type'];
    }
  }
  return $form;
}


/**
 * Implements hook_ting_search_get_controls().
 */
function bibdk_search_controls_ting_search_get_controls($form, $form_state) {

  $controls = array();

  $bibdk_search_controls = variable_get('bibdk_search_controls',array());

  foreach ( $bibdk_search_controls as $key => $control ) {
    $name = $control['name'];
    $s = ( isset($form_state['values'][ $control['name'] ]) ) ? $form_state['values'][ $control['name'] ] : '';
    if ( $control['type'] == 'checkboxes' ) {
      $s = explode('|',$s);
      foreach ( $s as $key => $val ) {
        $controls[ $control['name'] ][] = $val;
      }
    }
    else if ( $s != "" ) {
      $controls[ $control['name'] ] = $s;
    }
  }

  return $controls;
}


/**
 * Implements hook_theme().
 */
function bibdk_search_controls_theme() {
  $path = drupal_get_path('module', 'bibdk_search_controls') . '/theme';
  $bibdk_search_controls_theme_array = array(
    'bibdk_search_controls-admin-form' => array(
      'render element'  => 'form',
      'path'            => $path,
      'template'        => 'bibdk_search_controls-admin-form',
    ),
    'bibdk_search_controls-edit-form' => array(
      'render element'  => 'form',
      'path'            => $path,
      'template'        => 'bibdk_search_controls-edit-form',
    ),
    'bibdk_search_controls-values-form' => array(
      'render element'  => 'form',
      'path'            => $path,
      'template'        => 'bibdk_search_controls-values-form',
    ),
    'bibdk_search_controls-select' => array(
      'render element'  => 'form',
      'path'            => $path,
      'template'        => 'bibdk_search_controls-select',
    ),
    'bibdk_search_controls-radios' => array(
      'render element'  => 'form',
      'path'            => $path,
      'template'        => 'bibdk_search_controls-radios',
    ),
    'bibdk_search_controls-checkboxes' => array(
      'render element'  => 'form',
      'path'            => $path,
      'template'        => 'bibdk_search_controls-checkboxes',
    ),
  );
  return $bibdk_search_controls_theme_array;
}

